name: Build on tag

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' 
      timezone: Asia/Shanghai

jobs:
  Clone-Celeritas:
    runs-on: ubuntu-24.04
    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: Asia/Shanghai
      
      - name: Set time environment
        run: |
          echo "TIME=$(date +%s)" >> $GITHUB_ENV
    
      - name: Clone Celeritas
        run: git clone --single-branch --branch stonecutter https://git.taumc.org/embeddedt/celeritas.git

      - name: Reset to latest tag
        run: |
          cd celeritas
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          git reset --hard "$latest_tag"


      - name: Cache Celeritas Repository
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}
  Build-21-1:
    needs: Clone-Celeritas
    runs-on: ubuntu-24.04
    steps:
      - name: Restore Celeritas Repository Cache
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
         
      - name: Build
        run: |
          cd celeritas
          chmod +x ./gradlew
          ./gradlew -Ptarget_versions=1.21.1 packageJar --parallel

      - name: Remove other versions
        continue-on-error: true
        run: rm ./celeritas/build/libs/*-dev/*20.1-*.jar

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-1.21.1-builds
          path: "./celeritas/build/libs/*-dev/*"

      - name: Upload to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Celeritas Build 1.21.1 on tag
          automatic_release_tag: "celeritas-build-1.21.1-on-tag"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
          files: "./celeritas/build/libs/*-dev/*"
          prerelease: true

#  Build-21-10:
#    needs: Clone-Celeritas
#    runs-on: ubuntu-24.04
#    steps:
#      - name: Restore Celeritas Repository Cache
#        uses: actions/cache@v3
#        with:
#          path: ./celeritas
#          key: celeritas-repository-in-${{ env.TIME }}
#
#      - name: Setup JDK 21
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: 21
#         
#      - name: Build
#        run: |
#         cd celeritas
#          chmod +x ./gradlew
#          ./gradlew -Ptarget_versions=1.21.9 packageJar --parallel
#
#      - name: Upload to Artifact
#        uses: actions/upload-artifact@v4
#        with:
#         name: celeritas-1.21.10-builds
#          path: "./celeritas/build/libs/*-dev/*"
#
#      - name: Upload to Releases
#        uses: marvinpinto/action-automatic-releases@latest
#        with:
#          title: Celeritas Build 1.21.10
#          automatic_release_tag: "celeritas-build-1.21.10-on-tag"
#          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
#          files: "./celeritas/build/libs/*-dev/*"
#          prerelease: true

  Build-20-1:
    needs: Clone-Celeritas
    runs-on: ubuntu-24.04
    steps:
      - name: Restore Celeritas Repository Cache
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
         
      - name: Build
        run: |
          cd celeritas
          chmod +x ./gradlew
          ./gradlew -Ptarget_versions=1.20.1 packageJar --parallel

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-1.20.1-builds
          path: "./celeritas/build/libs/*-dev/*"

      - name: Upload to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Celeritas Build 1.20.1 on tag
          automatic_release_tag: "celeritas-build-1.20.1-on-tag"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
          files: "./celeritas/build/libs/*-dev/*"
          prerelease: true

  Build-18-2:
    needs: Clone-Celeritas
    runs-on: ubuntu-24.04
    steps:
      - name: Restore Celeritas Repository Cache
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
         
      - name: Build
        run: |
          cd celeritas
          chmod +x ./gradlew
          ./gradlew -Ptarget_versions=1.18.2 packageJar --parallel

      - name: Remove other versions
        continue-on-error: true
        run: rm ./celeritas/build/libs/*-dev/*20.1-*.jar

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-1.18.2-builds
          path: "./celeritas/build/libs/*-dev/*"

      - name: Upload to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Celeritas Build 1.18.2 on tag
          automatic_release_tag: "celeritas-build-1.18.2-on-tag"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
          files: "./celeritas/build/libs/*-dev/*"
          prerelease: true

  Build-16-5:
    needs: Clone-Celeritas
    runs-on: ubuntu-24.04
    steps:
      - name: Restore Celeritas Repository Cache
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
         
      - name: Build
        run: |
          cd celeritas
          chmod +x ./gradlew
          ./gradlew -Ptarget_versions=1.16.5 packageJar --parallel

      - name: Remove other versions
        continue-on-error: true
        run: rm ./celeritas/build/libs/*-dev/*20.1-*.jar

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-1.16.5-builds
          path: "./celeritas/build/libs/*-dev/*"

      - name: Upload to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Celeritas Build 1.16.5 on tag
          automatic_release_tag: "celeritas-build-1.16.5-on-tag"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
          files: "./celeritas/build/libs/*-dev/*"
          prerelease: true

  Build-12-2:
    needs: Clone-Celeritas
    runs-on: ubuntu-24.04
    steps:
      - name: Restore Celeritas Repository Cache
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
         
      - name: Build
        run: |
          cd celeritas
          chmod +x ./gradlew
          ./gradlew -Ptarget_versions=1.12.2 packageJar --parallel

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-1.12.2-builds
          path: "./celeritas/build/libs/*-dev/*"

      - name: Upload to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Celeritas Build 1.12.2 on tag
          automatic_release_tag: "celeritas-build-1.12.2-on-tag"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
          files: "./celeritas/build/libs/*-dev/*"
          prerelease: true

  Build-7-10:
    needs: Clone-Celeritas
    runs-on: ubuntu-24.04
    steps:
      - name: Restore Celeritas Repository Cache
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
         
      - name: Build
        run: |
          cd celeritas
          chmod +x ./gradlew
          ./gradlew -Ptarget_versions=1.7.10 packageJar --parallel

      - name: Remove other versions
        continue-on-error: true
        run: rm ./celeritas/build/libs/*-dev/*2.5-*.jar

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-1.7.10-builds
          path: "./celeritas/build/libs/*-dev/*"

      - name: Upload to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Celeritas Build 1.7.10 on tag
          automatic_release_tag: "celeritas-build-1.7.10-on-tag"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
          files: "./celeritas/build/libs/*-dev/*"
          prerelease: true

  Build-2-5:
    needs: Clone-Celeritas
    runs-on: ubuntu-24.04
    steps:
      - name: Restore Celeritas Repository Cache
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
         
      - name: Build
        run: |
          cd celeritas
          chmod +x ./gradlew
          ./gradlew -Ptarget_versions=1.2.5 packageJar --parallel

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-1.2.5-builds
          path: "./celeritas/build/libs/*-dev/*"

      - name: Upload to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Celeritas Build 1.2.5 on tag
          automatic_release_tag: "celeritas-build-1.2.5-on-tag"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
          files: "./celeritas/build/libs/*-dev/*"
          prerelease: true

  Build-b-7-3:
    needs: Clone-Celeritas
    runs-on: ubuntu-24.04
    steps:
      - name: Restore Celeritas Repository Cache
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
         
      - name: Build
        run: |
          cd celeritas
          chmod +x ./gradlew
          ./gradlew :babric:1.0.0-beta.7.3:packageJar --parallel

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-b1.7.3-builds
          path: "./celeritas/build/libs/*-dev/*"

      - name: Upload to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Celeritas Build beta-1.7.3 on tag
          automatic_release_tag: "celeritas-build-b1.7.3-on-tag"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
          files: "./celeritas/build/libs/*-dev/*"
          prerelease: true

  Build-b-8-1:
    needs: Clone-Celeritas
    runs-on: ubuntu-24.04
    steps:
      - name: Restore Celeritas Repository Cache
        uses: actions/cache@v3
        with:
          path: ./celeritas
          key: celeritas-repository-ontag-in-${{ env.TIME }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
         
      - name: Build
        run: |
          cd celeritas
          chmod +x ./gradlew
          ./gradlew :babric:1.0.0-beta.8.1:packageJar --parallel

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-b1.8.1-builds
          path: "./celeritas/build/libs/*-dev/*"

      - name: Upload to Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Celeritas Build beta-1.8.1 on tag
          automatic_release_tag: "celeritas-build-b1.8.1-on-tag"
          repo_token: "${{ secrets.UPLOAD_TO_RELEASE }}"
          files: "./celeritas/build/libs/*-dev/*"
          prerelease: true





